server:
  port: 9001
spring:
  application:
    name: food-client
  data:
    mongodb:
      host: localhost
      port: 27017
      database: project
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

